version: "3.9"
services:
  app:
    build:
      context: .
      target: laravel
    ports:
      - "8000:8000"
    depends_on:
      - vite
    environment:
      - APP_ENV=development
    volumes:
      - .:/app

  vite:
    build:
      context: .
      target: vite
      args:
        APP_ENV: development
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - .:/app
